### ISSUE TITLE
Coding standards resource enhancement

### ISSUE THREAD

**Issue by daften** [escapestudios-cookbooks/phpcs#2]
The resource now presumes the coding standard is in the root folder of the repository. However, e.g. for Drupal, this is not the case. There, there is a subfolder in the coder_sniffer module with the coding standards. I'll create a pull request with the enhancement of using a subfolder for this.

**Comment by djoos** [comment]
Hi @daften,

would you be able to point me to the phpcs Drupal coding standards? (~ [Symfony2 coding standard](https://www.github.com/escapestudios/Symfony2-coding-standard.git))

Thanks in advance!

Kind regards,
David

**Comment by daften** [comment]
Sure, it's part of this repository, as a subfolder: https://www.drupal.org/project/coder

**Comment by djoos** [comment]
Hi @daften,

this is obviously a *very* old issue - just wondering whether you made any progress here as otherwise I'll try and make some time to look into this issue...

Thanks!
David
