### ISSUE TITLE
#{Chef::Config[:file_cache_path] is meant as a temporary path

### ISSUE THREAD

**Issue by daften** [escapestudios-cookbooks/phpcs#5]
Not meant to install executables, e.g. phpcs to.
What I'd propose is the install composer and phpcs to /usr/local
What do you think?

**Comment by daften** [comment]
I'll make a PR which uses an attribute for the install location, with default a folder under /usr/local
Most of the code will remain the same, it's just some values.

**Comment by djoos** [comment]
Fixed in #5, thanks!

Kind regards,
David
